# Generated by Django 5.2.17 on 2026-09-28 12:16

import config.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['follower', 'created_at'], name='social_foll_followe_7ff834_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'followed'), name='unique_follow_pair'), models.CheckConstraint(condition=models.Q(('follower', models.F('followed')), _negated=True), name='no_self_follow')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=config.validators.post_image_upload_path, validators=[config.validators.validate_image_upload])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('repost_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reposts', to='social.post')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['author', '-created_at', '-id'], name='social_post_author__3d9dc2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('body', ''), ('image', ''), ('repost_of__isnull', False)), models.Q(('repost_of__isnull', True), models.Q(models.Q(('body', ''), _negated=True), models.Q(('image', ''), _negated=True), _connector='OR')), _connector='OR'), name='post_has_content_or_is_repost'), models.UniqueConstraint(condition=models.Q(('repost_of__isnull', False)), fields=('author', 'repost_of'), name='unique_user_repost')],
            },
        ),
    ]
